.github/SECURITY.md

Added the Security Policies and Procedures as taken from chocolatey/choco repository
This lives in the .github folder of each repository, so it makes sense to have it here to (hopefully) propagate to other repositories using these standard templates.
This is a markdown change so hasn't been tested.
N/A.

(doc) Add Security Policies and Procedures

---

.github/ISSUE_TEMPLATE/zFeatureRequest.md

Added content to the Feature template. This was taken from a combination of internal and Boxstarter templates (I thought the Boxstarter one was a good guide).
The Feature template was open with no headings to guide the person raising the issue.
This was markdown changes so no testing was done.
N/A.

(doc) Add content to Feature template

---

.github/ISSUE_TEMPLATE/zFeatureRequest.md

This pull request updates the issue reference section
for new feature / enhancement issue template to
instead of mentioning closing a issue to instead show
a list of issues they can provide.
This is done due to there not being any reason that a
new issue to close an existing issue.
Switching to a list of issues is done as it will show up
better if multiple issues are added.
N/A
N/A

(docs) Update issue reference in template

---

.github/ISSUE_TEMPLATE/zFeatureRequest.md
.github/ISSUE_TEMPLATE/zReportIssue.md

This PR updates the links in the issue templates to point to the correct file documenting where and how to submit issues across different projects.
To have a working link in the issue templates.
N/A
N/A

(doc) Correct link to submitting issue file

---

.github/licenses/apache-2.0.txt
.github/licenses/gpl-3.0.txt
.github/licenses/mit.txt
.github/licenses/workshop-apache-short.txt
.github/sync.yml
.github/workflows/file-sync.yml

This pull request adds a basic configuration file and a workflow to be able to synchronize files to other repositories.
Only repositories that are public, not empty, will currently be synchronized.
This will require the `choco-sync-bot` to have write access to all the listed repositories.
To keep files up to date.
1. A similar approach is being used in my own private organization. Unfortunately it is not possible to be 100% sure that it works as intended until it is merged.
Fixes #11

(#11) Add synchronization of files to remote repositories

---

.github/sync.yml

Adds label sync for the chocolatey-community/chocolatey-au repository
We need to ensure labels are standardised for this new repo.
N/A
N/A

(workflow) Add label sync for chocolatey-au

---

.github/labels.yml
.github/workflows/label-sync.yml
README.md
docs/labels-checklist.md
docs/labels.ps1

This pull request adds the needed documentation about how labels and files are synchronized, how new repositories can be added, how labels can be added and how new files can be added.
To document the synchronization.
N/A
#10  
#11

(#10, #11) Add documentation about the synchronize process

---

.github/PULL_REQUEST_TEMPLATE.md

Refactored the order of the questions. Added OS testing section  and other questions.
Makes it easier to read and provides checks on code changes being tested on what OS's.
N/A

(doc) Refactored and add OS testing section

---

CODE_OF_CONDUCT.md

This updates the e-mail address used to contact for code of conduct enforcement.
This address was not routed to the right folk. The new address is more appropriate.
1. We have tested that the new address is going somewhere appropriate
* ~[ ] Bug fix (non-breaking change).~
* ~[ ] Feature / Enhancement (non-breaking change).~
* ~[ ] Breaking change (fix or feature that could cause existing functionality to change).~
* ~[ ] PowerShell code changes.~

Updates Contact Details for Code of Conduct

---

.github/ISSUE_TEMPLATE/zReportIssue.yml

Adding check that person raising the GitHub issue is using official Chocolatey products.
Custoemrs may be using custom builds which we do not support.
N/A

(maint) Add official product check

---

.github/sync.yml

These changes include syncronizing the labels and
the pull request template to our fork of NuGet.Client.
This allows us to be sure that we use the same labels and pull request in that repository without having to manually verify it every time.
N/A
N/A
The same changes that was made in chocolatey/docs needs to be made for NuGet.Client.
IE to give `choco-sync-bot` write access to the repository.

(maint) Synchronize files to NuGet.Client

---

CODE_OF_CONDUCT.md

The first heading should be H1
The first heading was H3
This is just a change in markdown.
N/A
N/A

(doc) Update heading level

---

.github/ISSUE_TEMPLATE/zReportIssue.yml

Added a checkbox to ensure the status page has been checked.
Issues are being reported when there are unresolved status issues.
N/A
N/A
N/A

(maint) Added status page check

---

.github/sync.yml

This updates the synchronization list to include the community project Chocolatey-AU.
This should be a temporary synchronization that should be moved over to the community organization itself at some point.
Ensure that the Chocolatey-AU repository is synchronized with the standard templates.
N/A
N/A
N/A

(maint) Add Chocolatey-AU project to sync list

---

.github/sync.yml
.github/workflows/stale.yml

Adds file syncing of stale.yml file for the GitHub workflow.
We need a consistent policy for managing stale issues across our repositories.
This is currently working in chocolatey/choco repository and the file is a copy from there.
N/A
N/A

(maint) Add stale.yml file sync

---

.github/sync.yml

Add the stale and label sync to chocolatey-ansible repository.
Makes the repository more consistent.
N/A
N/A
N/A

(maint) Add chocolatey-ansible label and stale sync

---

.github/PULL_REQUEST_TEMPLATE.md

Updates "tested in PowerShell v2" to v3, and updates the example "tested on operating system(s)" a little.
We no longer require folk to test on PowerShell v2.
- No testing was performed.
* `[ ] Bug fix (non-breaking change).`
* `[ ] Feature / Enhancement (non-breaking change).`
* `[ ] Breaking change (fix or feature that could cause existing functionality to change).`
* `[ ] PowerShell code changes.`
* `[ ] Requires a change to the documentation.`
* `[ ] Documentation has been updated.`
* `[ ] Tests to cover my changes, have been added.`
* `[ ] All new and existing tests passed?`
* `[ ] PowerShell code changes: PowerShell v3 compatibility checked?`

Updates Pull Request Template With Changed Minimums

---

.github/ISSUE_TEMPLATE/zReportIssue.yml

Clarify the wording on the reproducible steps requirement.
Issues are still being submitted without them
N/A
N/A
N/A

(maint) Clarify reproducible steps requirement

---

.github/workflows/stale.yml

Upgrade to v9 of Stale which includes new functionality we need.
We need the new functionality to "unstale" an issue / PR when it's updated.
N/A
N/A
N/A

(maint) Upgrade to latest Stale version

---

.github/sync.yml

Adds the chocolatey/home repository for the stale workflow.
Need the stale workflow in there for issues.
N/A
N/A
N/A

(maint) Add chocolatey/home for Stale workflow

---

.github/workflows/stale.yml

A few changes:
* Made the action quotes consistent.
* Add a comment with the action GitHub.
* Added stale PR message.
* Added close issue reason.
Just some tidy up.
This is minor changes so haven't been tested.
N/A
N/A

(maint) Add close issue reason and stale PR message. Made consistent.

---

.github/sync.yml
.github/workflows/vote-for-issue.yml

When a new issue is created, add a comment with how to vote for the issue. Sync this to Chocolatey CLI, GUI and Licensed Issues repos.
We want to encourage voting for issues as it gives us information on what customers and community members prioritize.
N/A
N/A
N/A

(maint) Add voting comment to new issues

---

.github/sync.yml

Sync the Top Issues workflow to the chocolatey/ChocolateyGUI repository.
This is another repository that we want to encourage customers and community to vote for issues in.
This is currently working in chocolatey/choco and chocolatey/chocolatey-licensed-issues.
N/A
N/A

(maint) Sync Top Issues workflow to ChocolateyGUI repo

---

.github/workflows/top-issues.yml

Update to the latest version of the Top Issues workflow.
We're using a very old version.
N/A
N/A
N/A

(maint) Use latest GHA version
